### ISSUE TITLE
Limit on the selector

### ISSUE THREAD

**Issue by demiro** [kengz/reqscraper#2]
Hey... firstly, thanks for making this scraper wrapper for xray... does exactly what I need

the only issue that I have is I'd like to have more control on how much I want to take in, specially when setting it up (a lot of trail errors) and test.. I don't want to crawl through ALL the found links in the selector... just few... so since the cheerio doesn't come with jQuery's :lt(n) pseudo selector....(only via https://github.com/MatthewMueller/cheerio-soupselect)

was wondering... or if you could add soupselect so the selectors would support that or implement somekind of limit parameter I could pass.. like

``` javascript
    sc(
        'http://google.com',
        selector0
    )
    .limit(5)
    .then(function(result) {
        // prints the result
        console.log(JSON.stringify(result, null, 2));
    });
```

**Comment by eligiblekeng** [comment]
Hi there,

So this would have to be done from within the `xs` and `rxs` logic, by taking the first `n` of the `urlArr`, where `n` is the limit.
It would make more sense because `sc()` would have been called on all the links including the unwanted ones.

The latest push has this final argument added. Documentation update coming through soon.
